### ISSUE TITLE
Can you add some sample pictures

### ISSUE THREAD

**Issue by Max-Jesch** [djsudduth/mindmap-markdown#3]
Love the idea, but I am a bit hesitant to spend the time to set this up. If you could provide some sample pictures it would help to see wether this is the right thing for me. I guess many others feel the same. Thanks for your work in any case :-)

**Comment by djsudduth** [comment]
The samples are in the repo. Look at the /mindmaps and /markdown directories in code to see input and the output.

**Comment by djsudduth** [comment]
@Max-Jesch  - I assume you same the samples. I will add more in the README in the future.

**Comment by djsudduth** [comment]
Added in v-0.0.6
