### ISSUE TITLE
Errors on conversion

### ISSUE THREAD

**Issue by kevin-gwyrdh** [djsudduth/mindmap-markdown#4]
Really like this. Simplemind is a great tool but I work a lot in markdown and yes you are right the export is not so good. 
The test file works fine. 
However I have these errors when using my own files

`$ python3 mindmd.py -i mindmaps/test.smmx -o markdown/test.md

** Mindmap Markdown v-0.0.4 **

Mindmap: mindmaps/test.smmx ----> Markdown: markdown/test.md
Traceback (most recent call last):
  File "/home/gwyrdh/Downloads/mindmap-markdown-main/mindmd.py", line 527, in <module>
    main()
  File "/home/gwyrdh/Downloads/mindmap-markdown-main/mindmd.py", line 481, in main
    write_output(DEFAULT_MINDMAP, outfile, nums, vs)
  File "/home/gwyrdh/Downloads/mindmap-markdown-main/mindmd.py", line 362, in write_output
    sm_nodes = parse_mind_map(infile)
  File "/home/gwyrdh/Downloads/mindmap-markdown-main/mindmd.py", line 259, in parse_mind_map
    topic_node.guid = string_to_hexhash(topic.get('guid'), 16)
  File "/home/gwyrdh/Downloads/mindmap-markdown-main/mindmd.py", line 394, in string_to_hexhash
    hash_object = hashlib.sha3_384(alphanumeric_string.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
`
Simplemind version is 2.4.0 running in linux under wine

Any ideas especially the obvious that I have missed would be much appreciated :-)

**Comment by djsudduth** [comment]
Hey @kevin-gwyrdh - can you send me either the smmx file or the expanded `mindmap.xml` in the `document` folder? The error seems to be caused by a mindmap node that is missing a guid. 

Did the test smmx file  `HII Regions.smmx` that I included work for you?

You can email the file to don.james at pobox.com.  Thanks!

**Comment by kevin-gwyrdh** [comment]
Thank you @djsudduth I have emailed files. Looking at the xml output I think you are right three nodes do not have guid.
<topic id="5" parent="3" x="1084.00" y="832.00" text="plum" textfmt="plain"/>

Mindmap does not include top secret info. Added below
Looking at the 
![testmap](https://github.com/user-attachments/assets/6d2208e8-2c53-4d2f-828f-2cb98ab332fd)

**Comment by djsudduth** [comment]
@kevin-gwyrdh - ok, I think it is fixed now. Download just the `mindmd.py` file and let me know if you run into any problems. Odd that you're missing guids on some of the nodes.

**Comment by kevin-gwyrdh** [comment]
Hi @djsudduth That works fine. Thank you. Only slightly wierd thing text at the bottom of the markdown doc which I am sure is not in the document!!

- Relations:

Appreciate the speedy fix :-)

**Comment by djsudduth** [comment]
@kevin-gwyrdh glad it worked. Relations are connections between nodes that aren't part of the mindmap tree. For example

**Comment by kevin-gwyrdh** [comment]
Thanks. All good. Issue Closed :+1:
