### ISSUE TITLE
Better handle text formatting

### ISSUE THREAD

**Issue by szpak** [djsudduth/mindmap-markdown#6]
I had some balding used in the map. In XML is it:

```
... text="\\*Bold\\* regular" ...
```

Maybe it could be detected and replaced with the Markdown formatting (here `**Bold**` regular)? Possibly also for the other basic styles.

**Comment by szpak** [comment]
It seems better than just dropping out the formatting.

**Comment by djsudduth** [comment]
@szpak - formatting added and updated in new version

**Comment by szpak** [comment]
Thanks!

**Comment by djsudduth** [comment]
@szpak - were you able to test the formatting at all? I just want to make sure I didn't miss something.
